# sqlite
# PRAGMA FOREAIGN_KEYS = ON;
#
# DROP TABLE regions;
# CREATE TABLE regions (
#   id INTEGER PRIMARY KEY AUTOINCREMENT,
#   name VARCHAR(255) NOT NULL UNIQUE,
#   active BOOLEAN NOT NULL DEFAULT TRUE
# );
#
# DROP TABLE cities;
# CREATE TABLE cities(
#   id INTEGER PRIMARY KEY AUTOINCREMENT,
#   name VARCHAR(255) NOT NULL UNIQUE,
#   region_id INTEGER NOT NULL,
#   active BOOLEAN NOT NULL DEFAULT TRUE,
#   FOREIGN KEY (region_id) REFERENCES regions(id)
# );

# mysql

DROP TABLE IF EXISTS regions;
CREATE TABLE regions (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE InnoDB;

DROP TABLE IF EXISTS cities;
CREATE TABLE cities(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,
  region_id INTEGER NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  FOREIGN KEY (region_id) REFERENCES regions(id)
) ENGINE InnoDB;